# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2340c510642d1637daa6a3455aa73c2073bd55553930266f97399e0a33507059763406485916b401ce20799bf1faa191fbe3b7bb554f837711851128ab3bb91f

test:
  secret_key_base: 95653cb7d752c84813db98046119a7223e5b5b3ac518b057feb20a3e18b2c5984c2957492cde5c1d8533eb6e99361d589e7a72a488b038ccccd0b8fb9ec781f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
